kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: analytics
  name: mike-rolebinding
subjects:
- kind: User
  name: mike@acme.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: acme-admin
  apiGroup: rbac.authorization.k8s.io
