kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-viewers
subjects:
- kind: User
  name: cheryl@acme.com
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: cyril@acme.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: namespace-viewer
  apiGroup: rbac.authorization.k8s.io
